PROJECT_DIR: segmentation
MODEL:
  CHECKPOINT: None
DATA:
  ROOT: ./data
  BATCH_SIZE: 8
TRAIN:
  EPOCHS: 1000
  VAL_FREQ: 10
  LR: 3e-2
  WEIGHT_DECAY: 1e-3
  UNLABEL_WEIGHT: 0.1
  SAVE_BEST_ONLY: False